options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/github.com/xgurmanx/comp-4537-labs:$COMMIT_SHA'
    - '-f'
    - 'server/Dockerfile'
    - 'server'
